version: '2'
services:
  temporary_container:
    build:
      context: . 
      dockerfile: ./alerting/Dockerfile
    privileged: true      
    ports:
      - '5000:5000'
  quasar_cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: quasar_cadvisor
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    devices:
      - /dev/kmsg:/dev/kmsg
    depends_on:
      - sce-ledsign
      - sce-printer
  nginx:
    image: 'nginx'
    container_name: quasar_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
    restart: 'on-failure'
  quasar_prometheus:
    image: prom/prometheus:latest
    container_name: quasar_prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./monitoring/prometheus/:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - sce-ledsign
      - sce-printer
  alertmanager:
    image: prom/alertmanager:v0.23.0
    restart: on-failure
    ports: 
      - '9093:9093'
    volumes:
      - ./alertmanager:/config
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --cluster.advertise-address=0.0.0.0:9093
  discord-alerts:
    image: benjojo/alertmanager-discord
    container_name: discord-alerts
    restart: on-failure
    environment:
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK_URL}
volumes:
  alertmanager-data:
