groups: 
  - name: alert_rules
    interval: 15s
    rules: 
      - alert: container_not_running
        expr: |
          time() - container_last_seen{name="quasar_grafana"} > 10
            or
          time() - container_last_seen{name="quasar_nginx"} > 10
            or
          time() - container_last_seen{name="sce-ledsign"} > 10
            or
          time() - container_last_seen{name="sce-printer"} > 10
            or
          time() - container_last_seen{name="quasar_influx"} > 10
            or
          time() - container_last_seen{name="quasar_cadvisor"} > 10
            or
          time() - container_last_seen{name="quasar_grafana"} > 10
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Container "{{ $labels.name }}" is not running
          description: 'container "{{ $labels.name }}" has been down for more than {{ $value | printf "%.0f" }}'
      - alert: cant_ping_google
        expr: |
          metrics_for_google_dns{app="ping-temp"} < 1
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: cant ping google 
          description: 'Cant ping google bro'
      - alert: cant_ping_cloudflare
        expr: |          
          metrics_for_cloudflare_dns{app="ping-temp"} < 1 
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: cant ping cloudflar 
          description: 'Cant ping bro cloudflare'
      - alert: cant_ping_hawaiins
        expr: |
          metrics_for_some_random_hawaiian_gte_dns{app="ping-temp"} < 1
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: cant ping hawaii 
          description: 'Cant ping bro hawaii'
      - alert: cant_ping_badIP
        expr: |
          metrics_for_definitely_not_an_ip_address{app="ping-temp"} < 1
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: cant ping bad ip 
          description: 'Cant ping bro bad IP'

