groups: 
  - name: alert_rules
    interval: 15s
    rules:
      - alert: DeviceDown
        expr: time() - (device_last_seen / 1000) > 120
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'A device on the SCE network hasnt responded to pings'
          description: 'The {{$labels.deviceName}} ({{$labels.ipAddress}}) has been unresponsive for {{ $value | printf "%.0f" }} seconds'
      - alert: SNMPDown
        expr: time() - (last_snmp_response /1000) > 120
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: 'A device on the SCE network hasnt responded to snmpwalk'
          description: 'The {{$labels.deviceName}} ({{$labels.ipAddress}}) has been unresponsive for {{ $value | printf "%.0f" }} seconds to snmpwalk'
