groups: 
  - name: alert_rules
    interval: 15s
    rules:
      - alert: some_alert
        expr: have_you_ever_been < 1
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: Pinging Error 
          description: 'Cant Ping: {{ $labels.deviceName }}.'
