groups: 
  - name: alert_rules
    interval: 15s
    rules:
      - alert: Device_is_down
        expr: DeviceDown > 60
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: 'A device on the SCE network hasnt responded to pings'
          description: 'The {{$labels.deviceName}} ({{$labels.ipAddress}}) has been unresponsive for {{ $value | printf "%.0f" }} seconds'
