groups: 
  - name: alert_rules
    interval: 15s
    rules:
      - alert: Device_is_down
        expr: have_you_ever_been < 1
        for: 1s
        labels:
          severity: critical
        annotations:
          summary: 'A device on the internal network has not been responding to pings for 60 seconds'
          description: 'Cant Ping: ({{ $labels.deviceName }} IP:{{$labels.ipAddress}}).'
