global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'alerting-TEMPORARY'
    static_configs:
      - targets: ['temporary_container:5000']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - alert_rules.yml
